--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ThunderDoesPlugins/CustomFallDamagePE
build-by-default: true
branches:
- master
- worldguard
projects:
  CustomFallDamagePE:
    path: ""
    icon: "resources/icon.png"
...
