{
  #order of operation is: Multiply, Sum, Cutoff
  default-multiplier: 1, #1 for default
  multiplier: { #world name(case sensitive) not folder name, use worldtp list worlds to find world name
    # This works by damage = original damage * value
    world: 0.8, #only takes 80% of original dmg(aka reduce by 20%)
    hardcore: 3, #fall damage get multiplied by x3
    nofall: 0, #set fall damage to 0, anything * 0 = 0
  },

  default-sum: 0, #default sum
  sum: {
    #this works by summing the damage(after multiplier) and the value
    #due to technicalities, this only happen when player takes fall damage(3 block less fall will always be 0 dmg)
    world: -3, #-3 fall dmg
    hardcore: 5, #+5 to any fall dmg
  },

  default-cutoff: 0, #0 for default no cutoff
  cutoff: {
    world: 5 #anything below or equal to 5 will be reduced to 0
  },

  worldguard: false, #enable world guard support, must have world guard installed
  #this allows you to define custom fall damage modification for each regions
  #when a region is not defined, it will try to use the world, then default/global setting
  regions: { #world guard region settings
    area31: { #the region name(one with highest priority)
      multiplier: 0.7,
      sum: 5,
      cutoff: 8,
    },
  },

  playeronly: true, #ignore other non players entities(this applies for all worlds and regions)
}